### ISSUE TITLE
Auto implement `Default` if all properties have default

### ISSUE THREAD

**Issue by sahandevs** [maminrayej/tidy-builder#10]
#### Feature description

In structs that all properties have some type of default value:

```rust
    #[derive( tidy_builder::Builder)]
    pub struct Struct {
        #[builder(value = 1)]
        a: usize,
        #[builder(value = 2)]
        b: usize,
    }
```

it would be nice if the `Default` trait gets implemented automatically to avoid the following pattern:

```rust
    impl Default for Struct {
        fn default() -> Self {
            Self::builder().build()
        }
    }
```

#### Motivation
I've been using tidy-builder in my personal project. This feature request is because of [this part](https://github.com/sahandevs/dsp-blocks/blob/d869bc732d2166e5f19fba98584c6fd4ec28fef1/src/dsp.rs#L179-L190)/

**Comment by maminrayej** [comment]
Yes, seems reasonable. Should be easy to add since we only need to check if `req_fields` is empty or not.

**Comment by sahandevs** [comment]
Nice, is it okay if I open a pull request? If so, should I open it on the refactor branch?

**Comment by maminrayej** [comment]
Sure, go ahead.

> Nice, is it okay if I open a pull request? If so, should I open it on the refactor branch?

Open it on the `main` branch please since the refactor branch is not tested properly yet.
